django_project/django_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^events/', include('virtualornithology.interactions.urls', namespace="interactions")),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^timelines/', include('virtualornithology.timelines.urls', namespace="timelines")),
    url(r'^', include('virtualornithology.portraits.urls', namespace="portraits")),
)

django_project/virtualornithology/portraits/urls.py
from django.conf.urls import patterns, url
from .views import portraits_home, get_portrait, get_recommendations, view_portrait, follow, share, public_portraits


urlpatterns = patterns('',
    url(r'^perfiles/action/follow/$', follow, name='action-follow'),
    url(r'^perfiles/action/share/$', share, name='action-share'),
    url(r'^perfiles/api/public_portraits/$', public_portraits, name='get-public-portraits'),
    url(r'^perfiles/api/portrait/(?P<screen_name>\w+)/$', get_portrait, name='get-portrait'),
    url(r'^perfiles/api/recommendations/(?P<screen_name>\w+)/$', get_recommendations, name='get-recommendations'),
    url(r'^perfil/(?P<screen_name>\w+)/$', view_portrait, name='view-portrait'),
    url(r'^$', portraits_home, name='portraits-home'),
)

django_project/virtualornithology/timelines/urls.py
from django.conf.urls import patterns, url
from .views import last_timeline_json, timeline_home


urlpatterns = patterns('',
    url(r'^api/timeline/latest$', last_timeline_json, name='latest-timeline'),
    url(r'^$', timeline_home, name='timeline-home'),
)

django_project/virtualornithology/timelines/models.py
# coding=utf-8
from django.db import models
from django.core import serializers

try:
    import ujson as json
except ImportError:
    import json


class Timeline(models.Model):
    datetime = models.DateTimeField(auto_now_add=True, db_index=True)
    json = models.TextField()

    @classmethod
    def from_tweets(cls, tweets, metadata=None, **kwargs):
        """
        :param tweets: a iterable of tweets
        :param kwargs: extra attributes to be considered for inclusion. should be json serializable.
        :return:
        """

        tl = cls()

        json_tweets = json.loads(serializers.serialize("json", tweets));
        for key, values in kwargs.items():
            if len(values) != len(json_tweets):
                continue

            for tweet, value in zip(json_tweets, values):
                tweet['fields'][key] = value

        tl.save()

        json_repr = {'metadata': metadata, 'tweets': json_tweets, 'pk': tl.pk, 'created_at': tl.datetime.isoformat()}
        tl.json = json.dumps(json_repr)
        tl.save()
        return tl


class Interaction(models.Model):
    session = models.CharField(max_length=255, db_index=True)
    name = models.CharField(max_length=255, db_index=True)
    data = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)


# feedback and user information

from django.forms import ModelForm
from django.forms.widgets import Textarea, Select

LIKERT_7_CHOICES = (
    (1, '1 - Sin valor.'),
    (2, '2 - Poco valor.'),
    (3, '3 - Ligero valor.'),
    (4, '4 - Moderado valor.'),
    (5, '5 - Bastante valor.'),
    (6, '6 - Mucho valor.'),
    (7, '7 - Máximo valor.'),
    (8, 'Prefiero no decirlo'),
)

TWITTER_USER_TYPES = (
    ('UNK', 'Prefiero no decirlo.'),
    ('passive', 'Tengo cuenta, pero solamente leo tweets de otras personas.'),
    ('meformer', 'Publico tweets de interés sólo para mí y mis amigos(as).'),
    ('informer', 'Trato de discutir, informar e informarme respecto a los temas que me interesan.'),
    ('mix', 'A veces publico tweets no informativos, y otras intento discutir, informarme e informar.'),
    ('none', 'No uso Twitter.'),
)

class Feedback(models.Model):
    text = models.TextField(verbose_name='¿Qué te gusta, qué no te gusta, y qué mejorarías del sitio?')
    datetime = models.DateTimeField(auto_now_add=True, db_index=True)
    session = models.CharField(max_length=255, db_index=True)
    aesthetics = models.IntegerField(choices=LIKERT_7_CHOICES, default=8,
        verbose_name='De 1 a 7, ¿cómo valorarías la interfaz visual de la aplicación?')
    twitter_user_type = models.CharField(max_length=10, choices=TWITTER_USER_TYPES, default='UNK',
        verbose_name='¿Cuál de los siguientes perfiles se adapta más a tu uso de Twitter?')

class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback
        fields = ('aesthetics', 'text', 'twitter_user_type')
        widgets = {
            'aesthetics': Select(attrs={'class': 'form-control'}),
            'text': Textarea(attrs={'class':'input-xxlarge form-control'}),
            'twitter_user_type': Select(attrs={'class': 'form-control'}),
        }

django_project/virtualornithology/timelines/views.py
from django.shortcuts import render, render_to_response, redirect
from django.template import RequestContext
from user_agents import parse as agentparse
from virtualornithology.birds.views import check_referer
from virtualornithology.interactions.views import prepare_session
from .models import Timeline


def last_timeline_json(request):
    check_referer(request)
    latest = Timeline.objects.all().order_by('-datetime')[0]
    return render_to_response('json.html', {'json': latest.json}, context_instance=RequestContext(request), content_type='application/json')


def timeline_home(request, timeline_id=None):
    ua = agentparse(request.META.get('HTTP_USER_AGENT', ''))
    print(ua)
    print(request.GET)

    if ua.is_bot:
        return render_to_response('timelines/bots.html', context_instance=RequestContext(request))

    session = request.session
    print(session, session.session_key, session.items())
    prepare_session(request, 'all', 'aurora')

    return render_to_response('timelines/timeline-baseline.html', {
        'timeline_home_tweets': 10,
        'record_interactions': True,
        'current_app': 'aurora',
        'client_datetime_var': 'client_datetime'
    }, context_instance=RequestContext(request))

django_project/virtualornithology/timelines/templates/timelines/about.html
<div id="about-modal" class="modal fade">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
        <h4 class="modal-title">Acerca De "La Aurora Twittera"</h4>
      </div>
      <div class="modal-body">

  <div class="alert alert-info">
  <p><strong>¿Qué es la Aurora Twittera?</strong></p>
  <p>La Aurora Twittera es parte de la investigación doctoral de <a href="http://twitter.com/carnby" target="_blank"><span class="glyphicon glyphicon-user"></span> Eduardo Graells-Garrido</a>. Consiste en un proyecto donde realizamos análisis del contenido publicado
        por chilenas y chilenos en Twitter, con la idea de facilitar el acceso a información con diversidad geográfica, un problema que afecta a Chile debido
        a la centralización geográfica de nuestro país hacia la capital, Santiago.</p>
  </div>

  <div class="alert alert-success">
  <p><strong>¿Cómo funciona?</strong></p>

  <p>Constantemente estamos recolectando <i>tweets</i>, y cada 30 minutos elegimos un conjunto de ellos para presentar en nuestro <strong>resumen informativo</strong>. La idea principal es mostrar tweets que son
  publicados desde todas las regiones de Chile. <strong>La popularidad de un tweet no basta</strong> puesto que, habiendo muchos más twitteros y twitteras en Santiago, los tweets más populares
  tienden a ser <i>santiaguinos</i>.</p>
  </div>

  <div class="alert alert-warning">
  <p><strong>Otras consideraciones</strong></p>
  <p>Al ser parte de una investigación doctoral necesitamos saber un poco sobre quienes usan el sistema. Es importante mencionar que <strong>NO almacenamos información
  privada</strong>, solamente de interacción con la herramienta y la información que cada participante ha entregado voluntariamente.
  Esta información no es compartida con terceros.</p>
  </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cerrar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

django_project/virtualornithology/timelines/templates/timelines/bots.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>La Aurora Twittera de Chile</title>
</head>
<body>

<h1>La Aurora Twittera de Chile</h1>

<h2>¿Qué es la Aurora Twittera?</h2>
<p>La Aurora Twittera es parte de la investigación doctoral de <a href="http://twitter.com/carnby" target="_blank"><span class="glyphicon glyphicon-user"></span> Eduardo Graells-Garrido</a>. Consiste en un proyecto donde realizamos análisis del contenido publicado
    por chilenas y chilenos en Twitter, con la idea de facilitar el acceso a información con diversidad geográfica, un problema que afecta a Chile debido
    a la centralización geográfica de nuestro país hacia la capital, Santiago.</p>


<h2>¿Cómo funciona?</h2>

<p>Constantemente estamos recolectando <i>tweets</i>, y cada 30 minutos elegimos un conjunto de ellos para presentar en nuestro <strong>resumen informativo</strong>. La idea principal es mostrar tweets que son
publicados desde todas las regiones de Chile. <strong>La popularidad de un tweet no basta</strong> puesto que, habiendo muchos más twitteros y twitteras en Santiago, los tweets más populares
tienden a ser <i>santiaguinos</i>.</p>

<h2>Otras consideraciones</h2>
<p>Al ser parte de una investigación doctoral necesitamos saber un poco sobre quienes usan el sistema. Es importante mencionar que <strong>NO almacenamos información
privada</strong>, solamente de interacción con la herramienta y la información que cada participante ha entregado voluntariamente.
Esta información no es compartida con terceros.</p>


</body>
</html>

django_project/virtualornithology/timelines/templates/timelines/feedback-form.html
<div id="feedback-form-modal" class="modal fade">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">¡Gracias por visitar La Aurora Twittera!</h4>
      </div>
      <div class="modal-body">
            <form id="feedback-form" role="form">
            {% for field in feedback_form %}
                <div class="form-group">
                    <label class="control-label"><p>{{ field.label }}</p></label>
                    {% if field.help_text %}
                        <p class="help-block"><small>{{ field.help_text }}</small></p>
                    {% endif %}
                    {{ field }}
                </div>
            {% endfor %}
            </form>
      </div>
      <div class="modal-footer">
        <button id="feedback-form-button" type="button" class="btn btn-primary"><span class="glyphicon glyphicon-comment"></span> Enviar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
$().ready(function() {
    $('#feedback-form-button').click(function() {
        require(['d3'], function(d3) {
            var xhr = d3.xhr('{%  url 'timelines:timeline-feedback' %}');
            var cookie_value = get_cookie('csrftoken');
            if (cookie_value == null) {
                console.log('cookies disabled!');
                return;
            }

            xhr.header("X-CSRFToken", get_cookie('csrftoken'));
            xhr.header("Content-type", "application/x-www-form-urlencoded")

            var post_data = $('#feedback-form').serialize();

            console.log('post_data', post_data);

            xhr.post(post_data, function(error, response) {
                console.log(error);
                console.log(response);
                if (response.status == 200) {
                    console.log('user form sent!');
                    $('#feedback-form-modal').modal('hide');
                    $('#feedback-form-modal').remove();
                    $('div.modal-backdrop').remove();
                    $('#fb-form-li').remove();

                    require(['pnotify'], function(PNotify) {
                        $(function(){
                            new PNotify({
                                title: '¡Gracias!',
                                text: '<p>Gracias por enviarnos tu feedback. Lo usaremos para mejorar la aplicación.</p>',
                                type: 'info',
                            });
                        });
                    });
                }
            });
        });
    });
});
</script>

django_project/virtualornithology/timelines/templates/timelines/timeline-baseline.html
{% extends "site/base.html" %}

{% block navbar %}
{% endblock %}

<style>
{% block style %}
    body {
    height: 100%;
    overflow: hidden;
    font-face: Roboto;
}

#page-content-wrapper div.container-fluid {
    height: 100%;
    min-width: 405px;
    position: absolute;
    left: 0px;
    width: 100%;
    padding: 0;
    overflow-y: auto;
    overflow-x: hidden;
}

.footer {
    padding-top: 0.4em;
}

body {
    height: 100%;
    overflow: hidden;
}


#main div.container-fluid {
    height: 100%;
    min-width: 700px;
    min-height: 100%;
    overflow: hidden;
}

#timeline {
    min-height: 500px;
}
    {% include "timelines/timeline-treemap.css" %}
    {% include "timelines/simple-sidebar.css" %}
{% endblock %}
</style>

{% block before_navbar %}
{% include "timelines/about.html" %}
{% endblock %}

{% block nav_auth %}
{% endblock %}

{% block navbaritems_left %}
<li class="hidden-sm hidden-md"><a id="timeline-created-at">{{ created_at }}</a></li>
<li class="hidden-sm"><a href="#about" data-toggle="modal" data-target="#about-modal"><span class="glyphicon glyphicon-book"></span> ¿Cómo Funciona?</a></li>
{% endblock navbaritems_left %}


{% block sidebar %}
        <div id="location-filters" class="sidebar-nav list-group">
            <a id="todocl-logo" href="https://twitter.com/intent/user?screen_name=todocl" class="list-group-item">
                <img class="img img-rounded" src="{{ STATIC_URL }}assets/avatar_todocl_200x200.png" width="100%" style="margin: auto;" />
            </a>
            <a id="back-home" href="{% url 'portraits:portraits-home' %}" class="list-group-item"><span class="glyphicon glyphicon-home"></span> Perfiles Visuales</a>
            <a id="toggle-all-locations" href="#" class="list-group-item" style="color: white;"><span class="glyphicon glyphicon-th-large"></span> Titulares</a>
        </div>
{% endblock %}

{% block content %}
<div id="tweet-modal" class="modal fade">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cerrar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div id="timeline" style="position: relative;"></div>
{% endblock content %}

{% block footer %}
<!--
<div class="footer">
    <div class="container-fluid">
        <p class="hidden-sm hidden-md pull-right"><small>
        Por <a href="http://twitter.com/intent/user?screen_name=carnby">@carnby</a> |
            Nota: no estamos afiliados con Twitter.
        </small></p>
        <ul id="location-filters" class="list-inline" title="Puedes usar estos botones para mostrar solamente los tweets de una región particular.">
            <li><strong><button class="btn btn-default btn-xs disabled"><strong>Usa estos botones para elegir qué ver:</strong></button></strong></li>
            <li><strong><button id="toggle-all-locations" class="btn btn-info btn-xs">Todas las Regiones</button></strong></li>
        </ul>
    </div>
</div>
-->
{% endblock%}

{% block footer_script %}
<script>
/**
 * ¡Hola!
 * Gracias por ver mi código. No es muy bonito, pero es lo que hay ;) ¡Saludos!
 * -- Eduardo, @carnby
 */

{% include "javascript/require-config.js" %}

require(['d3', 'moment', 'underscore', 'aurora'], function(d3, moment, _, aurora) {
    moment.locale('es');
    console.log(aurora);

    var spinner = aurora.spinner('timeline');

    {% include "timelines/color-scales.js" %}
    {% include "timelines/interaction-logging.js" %}

    var categories = d3.map();
    var location_id_map = d3.map();
    var location_id = function(location_pk) { return location_id_map.get(location_pk); };

    {% include "timelines/location-filters.js" %}

    // window size
    var div = null;
    if (d3.select('#timeline').selectAll('div.aurora').empty()) {
        div = d3.select("#timeline").append('div').attr('class', 'aurora')
                .style("position", "relative");
    } else {
        div = d3.select('#timeline').select('div.aurora');
    }

    var timeline_container = div;

    {% include "timelines/window-size.js" %}

    timeline_container.style({
        "height": (height) + "px"
    });

    {% include 'timelines/timeline-treemap.js' %}
    {% include 'timelines/tweet-template.js' %}

    var showing_modal = false;
    vis_events.on('cell_click.modal', function(d, i) {
        console.log('click', this, d, i);
        var tweet = d.content;
        dispatcher.details.apply(this, [tweet, null]);

        d3.select('#tweet-modal .modal-body')
            .html('<ul class="detailed-tweet list-unstyled">' + tweet_template(tweet) + '</ul>')
            .selectAll('.detailed-tweet a')
            .on('click', function() {
                console.log('tweet click', this, tweet);
                dispatcher.click.apply(this, [tweet, d3.select(this).attr('href')]);
            });

        $('#tweet-modal').modal('show');
        showing_modal = true;
        //log_event({'name': 'aurora_cell_click', 'location': d.content.fields.geolocation})
    });

    vis_events.on('cell_exit.modal', function(d, i) {
        if (showing_modal) {
            $('#tweet-modal').modal('hide');
            showing_modal = false;
        }
    });

    filter_dispatcher.on('click.log', function(d) {
        log_event({'name': 'select_location', 'target': d.pk});
    });

    filter_dispatcher.on('show_all.log', function() {
        log_event({'name': 'show_all_locations'});
    });

    size_dispatcher.on('resize.treemap', function(width, height) {
        console.log('dispatcher', width, height);
        d3.entries(treemap).forEach(function(tmap) {
            tmap.value.size([width, height]);
        });
        font_size.range([min_font_size(width), max_font_size(width)]);
        console.log('resize!', width, height);
        render();
    });

    // fight!
    d3.json("{%  url 'timelines:latest-timeline' %}", function(error, json) {
        //current_data = json;

        if (json != null) {
            console.log('data', json);
            console.log('error', error);
            timeline_pk = json.pk;

            if (json.hasOwnProperty('created_at')) {
                d3.select('#timeline-created-at')
                    .html('<span class="glyphicon glyphicon-time"></span> Fecha de Edición: ' + moment(json.created_at).format('llll'));
            }

            json.tweets.forEach(function(d) {
                d.fields['has_media'] = d.fields.hasOwnProperty('media') && d.fields.media != null;
                if (d.fields.has_media == true) {
                    d.fields.media.forEach(function(m) {
                        m.fields.sizes = JSON.parse(m.fields.sizes);
                        m.fields.aspect_ratio = media_aspect_ratio(m);
                    });
                }
            });

            prepare_categories(json.metadata.locations, json.tweets);
            current_data = nest_by_location(json.tweets);

            render();
            dispatcher.loaded(screen);

            bind_twitter_events();
            init_interaction_logging();
        } else {
            aurora.notify('Error', 'Ha ocurrido un error. Por favor recarga la página en unos momentos.', 'error');
        }

        aurora.notify('Bienvenido al <strong>Timeline Descentralizado</strong>',
                'Cada 30 minutos generamos un resumen informativo basado en tweets publicados en todo Chile. ' +
                'Para más información puedes revisar el link "¿Cómo funciona?" en la barra superior.',
                'info');

        aurora.notify('Nota',
                'Los tweets están agrupados de acuerdo a la región en la que fueron publicados. Puedes hacer clic en cada recuadro para ver los detalles del tweet.',
                'success');

        spinner.stop();
    });
});

</script>
{% endblock %}

django_project/virtualornithology/timelines/templates/timelines/timeline-clustered.html
{% extends "timelines/timeline-baseline.html" %}

{% block render_function %}
    {% include "timelines/timeline-clustered.js" %}
{% endblock render_function %}

django_project/virtualornithology/timelines/templates/timelines/timeline-mobile-baseline.html
<!DOCTYPE html>
 <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <title>La Aurora Twittera de Chile</title>
    <link href="{{ STATIC_URL }}libs/bootstrap-3.2.0-dist/css/bootstrap-darkly.min.css" rel="stylesheet" />
    <link href='{{ STATIC_URL }}libs/pnotify/pnotify.custom.min.css' rel='stylesheet' type='text/css'>

    <script src="{{ STATIC_URL }}libs/require.js"></script>
    <script src="{{ STATIC_URL }}libs/modernizr.custom.js"></script>
    <script src="{{ STATIC_URL }}libs/jquery-1.7.2.min.js"></script>
    <script src="{{ STATIC_URL }}libs/bootstrap-3.2.0-dist/js/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}libs/pnotify/pnotify.custom.min.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block header %}
    {% endblock%}

    <style>
    body {
        height: 100%;
    }

    .navbar-header {
        width: 100%;
    }

    .container-fluid {
        width: 95%;
    }

    .footer {
        padding-top: 0.4em;
    }

    .jumbotron {
        text-align: center;
    }

    {% block style %}
        div.single-tweet { margin: auto; margin-bottom: 1em; }
        div.single-tweet div.panel { margin-bottom: 5px; }
        div.panel-footer { padding: 4px 15px; border-top: none; }
        #timeline { margin: auto; padding-top: 1em; }
        div.aurora { margin: auto; }

        {% if approach == 'clustered' %}
        div.clustered-tweets { margin: auto; }
        div.clustered-tweets div.panel { margin-bottom: 5px; }
        div.panel-heading { padding: 4px 15px; border-bottom: none; }
        {% endif %}
    {% endblock style %}
    </style>
</head>

<body>



{% include "timelines/about.html" %}


<div id="main">
    <div class="container-fluid">
        <div class="jumbotron">
            <h1><a href="#about" data-toggle="modal" data-target="#about-modal">Aurora Twittera de Chile</a></h1>
            <p id="timeline-created-at" class="muted"></p>
        </div>
        {% block content %}
        <div id="timeline" class="panel-group">
        </div>
        {% endblock content %}

        <hr />
        {% block footer %}
        <div class="footer">
            <p><small>
            Un experimento de <a href="http://twitter.com/intent/user?screen_name=carnby">@carnby</a> | <a href="http://ficciones.cl" target="_blank">ficciones</a> |
                <a href="http://carnby.github.io" target="_blank">github</a>.
            </small></p>
        </div>
        {% endblock%}
    </div>
</div>

{% autoescape off %}
<script>
/**
 * ¡Hola!
 * Gracias por ver mi código. No es muy bonito, pero es lo que hay ;) ¡Saludos!
 * -- Eduardo, @carnby
 */

{% include "timelines/csrf-cookie.js" %}
{% include "timelines/require-config.js" %}

require(['d3', 'moment', 'underscore', 'spin'], function(d3, moment, _, Spinner) {
    moment.locale('es');
    {% include "timelines/spinner.js" %}
    {% include "timelines/tweet-template.js" %}

    {% if approach != 'baseline' %}
    var nest_by_location = function(data) {
        var nest = d3.nest().key(function(d) {
            return +d.fields.geolocation;
        });
        var nested = nest.entries(data);

        var entries = {key: 'root', children: [], weight: 0};

        nested.forEach(function(d, i) {
            var location = {key: 'location-' + d.key, pk: d.key};
            location.children = d.values.map(function(tweet) {
               return {key: 'tweet-' + tweet.pk, content: tweet, children: null, parent: d, weight: tweet.fields.weight};
            });
            entries.children.push(location);
        });

        entries.children.forEach(function(d) {
            d.weight = d3.sum(d.children, function(e) { return e.weight});
        });

        entries.weight = d3.sum(entries.children, function(e) { return e.weight});

        return entries;
    };
    {% endif %}

    {% include "timelines/color-scales.js" %}
    {% include "timelines/interaction-logging.js" %}

    var categories = d3.map();
    var location_id_map = d3.map();
    var location_id = function(location_pk) { return location_id_map.get(location_pk); };

    {% include "timelines/location-filters.js" %}

    var current_data = null;
    var current_tweet_data = function() {
        return current_data.tweets;
    };


    {% include "timelines/twitter-logging.js" %}
    {% include "timelines/window-size.js" %}

    {% block render_function %}
    {% include "timelines/timeline-baseline.js" %}
    {% endblock render_function %}

    // fight!
    {% if timeline_id %}
    d3.json("{%  url 'timelines:timeline-id' timeline_id %}", function(error, json) {
    {% else %}
    d3.json("{%  url 'timelines:latest-timeline' %}", function(error, json) {
    {% endif %}
        spinner.stop();
        current_data = json;

        if (error == null) {
            console.log('data', current_data);
            console.log('error', error);
            timeline_pk = current_data.pk;

            if (current_data.hasOwnProperty('created_at')) {
                d3.select('#timeline-created-at')
                    .html(moment(current_data.created_at).format('LLLL'));
            }

            prepare_categories(current_data.metadata.locations, current_data.tweets);
            render(current_tweet_data());
            log_event({'name': 'loaded', 'screen_width': screen.width, 'screen_height': screen.height});
            timer_id = window.setInterval(send_events, 1000 * n_seconds);
            bind_twitter_events();
        } else {
            require(['pnotify'], function(PNotify) {
                $(function(){
                    new PNotify({
                        title: 'Error',
                        text: '<p>Ha ocurrido un error. ¿Has ingresado una URL válida?</p>',
                        delay: 8000,
                        type: 'error'
                    });
                });
            });
        }
    });
});

</script>
{% endautoescape %}
<!-- {% csrf_token %} -->
</body>
</html>

django_project/virtualornithology/timelines/templates/timelines/timeline-mobile-clustered.html
{% extends "timelines/timeline-mobile-baseline.html" %}

{% block render_function %}
    {% include "timelines/timeline-clustered.js" %}
{% endblock render_function %}

django_project/virtualornithology/timelines/templates/timelines/timeline-treemap.html
{% extends "timelines/timeline-baseline.html" %}

{% block style %}
    {% include "timelines/timeline-treemap.css" %}
{% endblock style %}

{% block navbaritems %}
<li><a id="legend-link" href="#"><span class="glyphicon glyphicon-th-large"></span> Ver/Esconder Leyenda</a></li>
{% endblock navbaritems %}

{% block render_function %}
    {% include "timelines/timeline-treemap.js" %}
{% endblock render_function %}