django_project/django_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^events/', include('virtualornithology.interactions.urls', namespace="interactions")),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^timelines/', include('virtualornithology.timelines.urls', namespace="timelines")),
    url(r'^', include('virtualornithology.portraits.urls', namespace="portraits")),
)

django_project/virtualornithology/portraits/urls.py
from django.conf.urls import patterns, url
from .views import portraits_home, get_portrait, get_recommendations, view_portrait, follow, share, public_portraits


urlpatterns = patterns('',
    url(r'^perfiles/action/follow/$', follow, name='action-follow'),
    url(r'^perfiles/action/share/$', share, name='action-share'),
    url(r'^perfiles/api/public_portraits/$', public_portraits, name='get-public-portraits'),
    url(r'^perfiles/api/portrait/(?P<screen_name>\w+)/$', get_portrait, name='get-portrait'),
    url(r'^perfiles/api/recommendations/(?P<screen_name>\w+)/$', get_recommendations, name='get-recommendations'),
    url(r'^perfil/(?P<screen_name>\w+)/$', view_portrait, name='view-portrait'),
    url(r'^$', portraits_home, name='portraits-home'),
)

django_project/virtualornithology/timelines/urls.py
from django.conf.urls import patterns, url
from .views import last_timeline_json, timeline_home


urlpatterns = patterns('',
    url(r'^api/timeline/latest$', last_timeline_json, name='latest-timeline'),
    url(r'^$', timeline_home, name='timeline-home'),
)

django_project/virtualornithology/portraits/models.py
from django.db import models


class Portrait(models.Model):
    auth_screen_name = models.CharField(max_length=100, db_index=True, default='')
    auth_id_str = models.CharField(max_length=100, default='')
    public_access_enabled = models.BooleanField(default=True)
    access_token = models.CharField(max_length=255)
    access_token_secret = models.CharField(max_length=255)
    demo_portrait = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    last_update_date = models.DateTimeField(null=True, default=None)
    last_tweet_date = models.DateTimeField(null=True, default=None)
    last_tweet_id = models.CharField(max_length=255, null=True, default=None)
    last_access = models.DateTimeField(null=True, default=None)
    portrait_content = models.TextField(null=True, default=None)
    portrait_preferences = models.TextField(null=True, default=None)
    portrait_recommendations = models.TextField(null=True, default=None)
    user_data = models.TextField(null=True)
    has_political_content = models.NullBooleanField(null=True, default=None)
    condition_ui = models.CharField(max_length=25, null=True, default=None, choices=(('baseline', 'Baseline'), ('bubbles', 'Circle Packing')))
    condition_rec = models.CharField(max_length=25, null=True, default=None, choices=(('kls', 'Kullback-Leibler Similarity'), ('it_score', 'Intermediary Topics Score')))
    # some users remove permissions. we delete them.
    active = models.BooleanField(default=True)
    # feature on the home page
    featured_on_home = models.BooleanField(default=False)
    # last time user was mentioned
    last_notification_date = models.DateTimeField(null=True, default=None)

django_project/virtualornithology/portraits/views.py
from django.shortcuts import get_object_or_404, render_to_response
from django.http import Http404
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.views.decorators.gzip import gzip_page
from .models import Portrait
from .tasks import portrait_follow, portrait_share
from virtualornithology.interactions.views import prepare_session
from virtualornithology.birds.views import render_json

try:
    import ujson as json
except ImportError:
    import json


@gzip_page
def get_portrait(request, screen_name):
    portrait = get_object_or_404(Portrait, auth_screen_name=screen_name.lower(), active=True)

    if not portrait.public_access_enabled:
        if request.user.username.lower() != screen_name.lower():
            raise PermissionDenied()

    return render_json(request, portrait.portrait_content, dumped=True)


@gzip_page
@login_required
def get_recommendations(request, screen_name):
    if request.user.username.lower() == screen_name.lower():
        portrait = get_object_or_404(Portrait, auth_screen_name=screen_name.lower(), active=True)
        return render_json(request, portrait.portrait_recommendations, dumped=True)

    raise PermissionDenied()


# @login_required
def view_portrait(request, screen_name):
    print(screen_name)
    portrait = get_object_or_404(Portrait, auth_screen_name=screen_name.lower(), active=True)

    if not portrait.public_access_enabled:
        if not request.user.is_authenticated() or request.user.username.lower() != screen_name.lower():
            return render_to_response('portraits/protected.html', {
                'portrait_screen_name': screen_name,
                'portrait_pk': portrait.pk,
                'profile_data': json.dumps(portrait.user_data)
            }, context_instance=RequestContext(request))

    if not portrait.portrait_content:
        return render_to_response('portraits/wait.html', {
            'portrait_screen_name': screen_name,
            'portrait_pk': portrait.pk,
            'profile_data': json.dumps(portrait.user_data),
            'demo_portrait': portrait.demo_portrait
        }, context_instance=RequestContext(request))

    record_interactions = False
    show_recommendations = False

    if request.user.is_authenticated():
        record_interactions = True
        auth_portrait = Portrait.objects.get(auth_screen_name=request.user.username.lower(), active=True)

        if auth_portrait == portrait:
            show_recommendations = True
            portrait.last_access = timezone.now()
            portrait.save()

        if not 'experimental_group' in request.session or not 'portraits' in request.session['experimental_group']:
            print('preparing session')
            prepare_session(request, '{0}_{1}'.format(auth_portrait.condition_ui, auth_portrait.condition_rec), 'portraits')
            print(request.session)

    return render_to_response('portraits/portrait.html', {
        'portrait_screen_name': screen_name,
        'portrait_current_pk': portrait.pk,
        'condition_ui': portrait.condition_ui,
        'condition_rec': portrait.condition_rec,
        'last_update': portrait.last_update_date.isoformat(),
        'demo_portrait': portrait.demo_portrait,
        'show_recommendations': show_recommendations,
        'record_interactions': record_interactions,
        'current_app': 'portraits',
        'client_datetime_var': 'client_datetime'
    }, context_instance=RequestContext(request))


@gzip_page
def public_portraits(request):
    portraits = Portrait.objects.exclude(Q(portrait_content=None)|Q(active=False)|Q(public_access_enabled=False)).filter(featured_on_home=True).order_by('-created_on')
    # we need to concat json
    user_data = portraits.values_list('user_data', flat=True)
    users = '[{0}]'.format(u','.join(user_data[0:50]))
    return render_json(request, users, dumped=True)


def portraits_home(request):
    return render_to_response('portraits/index.html', {'n_portraits': 50}, context_instance=RequestContext(request))


# actions
@login_required
def follow(request):
    #print 'follow'
    #print request.POST
    auth_user = request.user

    source_user = request.POST.get('source', '')
    if not source_user or auth_user.username != source_user:
        print(auth_user.username, len(auth_user.username), source_user, len(source_user))
        raise PermissionDenied

    portrait = get_object_or_404(Portrait, auth_screen_name=auth_user.username.lower())

    target_user_id = request.POST.get('target', '')[:100]
    if not target_user_id:
        raise Http404

    try:
        followed = portrait_follow(portrait, target_user_id)
    except:
        followed = False

    return render_json(request, followed)


@login_required
def share(request):
    auth_user = request.user

    source_user = request.POST.get('source', '')
    if not source_user or auth_user.username.lower() != source_user.lower():
        print(auth_user.username, len(auth_user.username), source_user, len(source_user))
        raise PermissionDenied

    portrait = get_object_or_404(Portrait, auth_screen_name=auth_user.username.lower())

    try:
        followed = portrait_share(portrait)
    except Exception as err:
        print(err)
        followed = False

    print('share result', followed)

    return render_json(request, followed)

django_project/virtualornithology/portraits/templates/portraits/abstract.html
{% extends "site/base.html" %}

{% block header %}
<style>
/* Non-responsive overrides
 *
 * Utilitze the following CSS to disable the responsive-ness of the container,
 * grid system, and navbar.
 */

/* Reset the container */
.container {
  max-width: none !important;
  width: 970px;
}

/* Demonstrate the grids */
.col-xs-4 {
  padding-top: 15px;
  padding-bottom: 15px;
  background-color: #eee;
  border: 1px solid #ddd;
  background-color: rgba(86,61,124,.15);
  border: 1px solid rgba(86,61,124,.2);
}

.container .navbar-header,
.container .navbar-collapse {
  margin-right: 0;
  margin-left: 0;
}

div.popover {
    width: 400px;
    max-width: none;
}
</style>
<script type="text/javascript" src="{{ STATIC_URL }}libs/polygon.intersection.js"></script>
{% endblock%}

{% block content %}
<div id="keywords" class="panel-body"></div>
{% endblock %}


{% block footer_script %}
<script src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
<script type="text/javascript" src="{{ STATIC_URL }}libs/polygon.intersection.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}vis/portrait-tweets.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}vis/portrait-common.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}vis/portrait-abstract.js"></script>

<script type="text/javascript">

(function() {
var portrait = window.portrait; 

d3.json("{%  url 'portraits:get-portrait' user.username %}", function(error, json) {
    console.log(json);
    window.json_response= json;
    portrait.draw_profile(json.fields.user);
    portrait.init_data(json);
});
}).call(this);

/*
    if (false) {
        background.selectAll('rect.qt').data(rects)
            .enter()
            .append('rect')
            .attr('class', 'qt')
            .attr('width', function(d) {
                return d.width;
            })
            .attr('height', function(d) {
                return d.height;
            })
            .attr('x', function(d) {
                return d.x;
            })
            .attr('y', function(d) {
                return d.y;
            })
            .attr('fill', function(d) {
                if (d.inside) {
                    return 'red';
                } else {
                    return 'gray';
                }
            })
            .attr('opacity', 0.1)
            .attr('stroke', 'gray')
            .attr('stroke-width', 1);
    }
});
*/
</script>



{% endblock %}

django_project/virtualornithology/portraits/templates/portraits/baseline.html
{% extends "site/base.html" %}

{% block header %}
<style>
/* Non-responsive overrides
 *
 * Utilitze the following CSS to disable the responsive-ness of the container,
 * grid system, and navbar.
 */

/* Reset the container */
.container {
  max-width: none !important;
  width: 970px;
}

/* Demonstrate the grids */
.col-xs-4 {
  padding-top: 15px;
  padding-bottom: 15px;
  background-color: #eee;
  border: 1px solid #ddd;
  background-color: rgba(86,61,124,.15);
  border: 1px solid rgba(86,61,124,.2);
}

.container .navbar-header,
.container .navbar-collapse {
  margin-right: 0;
  margin-left: 0;
}

</style>
<script type="text/javascript" src="{{ STATIC_URL }}libs/polygon.intersection.js"></script>
{% endblock%}

{% block navbar %}
{% endblock %}

{% block content %}
<h1>Proyecto: Virtual Portraits</h1> 

<div id="profile-info"></div>    

<div>
  <div class="panel panel-default">
    <div class="panel-heading">Nube de Conceptos, Menciones y Hashtags frecuentes y con mayor presencia en el tiempo</div>
    <div id="keywords" class="panel-body"></div>
    <div class="panel-footer"><span class="label label-info">Instrucciones</span> Cliquea un concepto o palabra para ver <em>tweets</em> asociados a ella. A la izquierda se desplegar&aacute;n tus tweets y a la derecha los tweets recomendados.</div>
  </div>

</div>

<div class="row">
    <div class="col-md-6">
        <div id="portrait-tweets" ></div>
    </div>
        
    <div class="col-md-6">
        <div id="recommended-tweets" ></div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
<script type="text/javascript" src="{{ STATIC_URL }}vis/portrait-common.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}vis/portrait-tweets.js"></script>
<script type="text/javascript">

var portrait = window.portrait;

portrait.initialize(908, 400);

d3.json("/site/assets/portraits/{{ screen_name }}.json", function(error, json) {
//d3.json("/api/portraits/get/{{ screen_name }}", function(error, json) {
    console.log(json);
    portrait.draw_profile(json.fields.user);
    portrait.init_data(json);
});
</script>



{% endblock %}

django_project/virtualornithology/portraits/templates/portraits/index.html
{% extends "site/base.html" %}

{% block header %}
<link href='{{ STATIC_URL }}css/non-responsive.css' rel='stylesheet' type='text/css'>
<link href='{{ STATIC_URL }}matta-libs/matta.css' rel='stylesheet' type='text/css'/>
{% endblock %}

<style>
{% block style %}

body {
    padding-top: 2px;
}

.header {
    margin-top: 10px;
    margin-bottom: 10px;
}

#public-portraits h3 {
    margin-top: 5px;
    margin-bottom: 5px;
    font-size: 18px;
    font-weight: bold;
}

a.navbar-brand {
    color: silver;
    font-weight: bold;
}

.thumbnail {
    border: none;
    margin-bottom: 5px;
}

.thumbnail .caption {
    overflow-x: hidden;
}

.thumbnail p {
    margin-bottom: 0;
}

#who-to-follow {
    padding-top: 10px;
    height: 610px;
    overflow-y: 'auto';
}
#who-to-follow .recommendation {
    padding: 5px;
    padding-left: 10px;
}

#who-to-follow .recommendation hr {
    margin-top: 10px;
    margin-bottom: 10px;
}

div.panel-heading button {
    margin-top: -5px;
    margin-left: 5px;
}

.inactive_circle {
    fill: silver;
    stroke: silver;
}

p.help-text {
    margin-top: 100px;
}

.panel-visualization .panel-body {
    padding: 0;
}

img.img-user-avatar {
margin: auto;
}

.header a.navbar-brand {
    height: 40px;
}

{% block extra_style %}
{% endblock %}
{% endblock %}
</style>

{% block navbar %}
{% endblock %}

{% block main_sidebar %}
{% endblock main_sidebar %}

{% block container %}
<div id="main" class="container">
  <div class="header">
    <nav>
      <ul class="nav nav-pills pull-left">
        <li><a class="navbar-brand" href="{% url 'portraits:portraits-home' %}">La Aurora Twittera de Chile</a></li>
      </ul>
      <ul class="nav nav-pills pull-right">
            <li role="presentation"><a href="{% url 'timelines:timeline-home' %}"><span class="glyphicon glyphicon-th"></span> Timeline Descentralizado</a></li>
        {% if user.is_authenticated %}
            <li role="presentation"><a href="{% url 'portraits:view-portrait' user.username %}"><span class="glyphicon glyphicon-user"></span> @{{ user.username }}</a></li>
            <li role="presentation"><a href="{% url 'auth:logout' %}?next={% url 'portraits:portraits-home' %}"><span class="glyphicon glyphicon-log-out"></span> Cerrar Sesión</a></li>
        {% else %}
            <li role="presentation"><a href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}"><span class="glyphicon glyphicon-log-in"></span> Crea tu <em>Perfil Visual</em> (Login)</a></li>
        {% endif %}
      </ul>
    </nav>
    <span class="clearfix"></span>
  </div>

{% block body_content %}
  <div class="jumbotron clearfix">
    <h2><strong>Perfiles Visuales</strong> <small>@ Aurora Twittera</small></h2>
    <p class="lead">Los <em>Perfiles Visuales</em> son representaciones interactivas de tu perfil en Twitter, cuyo propósito es <em>ver y explorar</em> tweets
    de una manera distinta. Puedes explorar los perfiles de demostración que hemos creado o bien <strong>crear tu propio perfil</strong>.</p>

    <p>Cada día actualizaremos tu perfil de acuerdo a la actividad que tengas en Twitter.
        Además, basándonos en el contenido de tus tweets, en cada actualización generaremos un conjunto de cuentas sugeridas para ti.
        El algoritmo que estima a quién sugerir está influenciado por la idiosincracia y realidad chilena.
        Pruébalo, no seas <em>tímid@</em>, y no olvides seguirnos en <strong><a href="https://twitter.com/intent/user?screen_name=todocl">@todocl</a></strong> ;)</p>

    <p>
    {% if user.is_authenticated %}
        <a class='btn btn-lg btn-primary' href="{% url 'portraits:view-portrait' user.username %}"><span class="glyphicon glyphicon-user"></span> @{{ user.username }}</a>
        <a class='btn btn-lg btn-warning' href="{% url 'auth:logout' %}?next={{ request.path }}"><span class="glyphicon glyphicon-log-out"></span> Cerrar Sesión</a>
    {% else %}
        <a class='btn btn-lg btn-success' href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}"><span class="glyphicon glyphicon-log-in"></span> Crea tu <em>Perfil Visual</em> (Login)</a>
    {% endif %}
    </p>

  <p><small>Si buscas nuestro anterior experimento de <em>Timelines Descentralizados</em>, puedes ver una nueva versión beta <a href="{% url 'timelines:timeline-home' %}">aquí</a>.</small></p>
  </div>

    <h3>Información del Proyecto</h3>
      {% if not user.is_authenticated %}
    <p><span class="label label-warning">Permisos</span> No modificaremos tu perfil ni publicaremos tweets automáticos.
        Seguiremos a quienes desees hacerlo o publicaremos un tweet para compartir tu perfil solamente si tú lo indicas.</p>

    <p><span class="label label-success">Nosotros</span> Este proyecto es parte de una investigación doctoral sobre representación visual de información. Ante cualquier duda puedes contactar a <strong><a href="https://twitter.com/intent/user?screen_name=carnby">@carnby</a></strong>.</p>
  {% else %}
    <p><span class="label label-warning">Permisos</span> Tu perfil es actualizado aproximadamente cada 24 horas. Si deseas desactivarlo basta que en Twitter le quites los
    permisos de acceso a la Aurora Twittera. Por favor, considera que dicho proceso no es instantáneo.</p>
  {% endif %}

      <p><span class="label label-info">Acceso</span> Si tu cuenta es protegida (tiene candado), tu perfil no podrá ser visto por nadie más que tú.</p>

<hr />

        <h3>Perfiles Visuales de Demostración</h3>
        <p>Los siguientes perfiles han sido creados como demostración del sistema. Son cuentas y personas que hemos encontrado en la <em>Twittósfera Chilena</em> y nos parecen
            interesantes o adhocs a la contingencia del momento.
           Mostramos los últimos <strong>{{ n_portraits }}</strong> perfiles que hemos creado.
           Si quieres ver un perfil que no está en esta lista porque lo creamos con anterioridad, puedes buscar el link en nuestro <em><a href="https://twitter.com/intent/user?screen_name=todocl">timeline</a></em>.</p>

        <div id="public-portraits"></div>

{% endblock body_content %}
    <footer class="footer">
        <hr />
        <p><small>Esta es una investigación sobre exploración visual de contenido en redes sociales, en el contexto de la tesis doctoral de <strong><a href="https://twitter.com/intent/user?screen_name=carnby">@carnby</a></strong> |
            Síguenos en <strong><a href="https://twitter.com/intent/user?screen_name=todocl">@todocl</a></strong> |
            Construido con
                <a href="http://d3js.org/" target="_blank">d3.js</a>,
                <a href="https://github.com/carnby/matta" target="_blank">matta</a>,
                <a href="http://radimrehurek.com/gensim/" target="_blank">gensim</a>,
                <a href="https://www.djangoproject.com/" target="_blank">django</a>,
                <a href="http://getbootstrap.com/" target="_blank">bootstrap</a> |
                Puedes bajar el código fuente en <a href="https://github.com/carnby/aurora/" target="_blank">github</a>
                Este sitio funciona mejor en Chrome.
        </small>
        </p>
    </footer>

</div> <!-- /container -->

{% endblock container %}

{% block footer_script %}
<script>

/**
 * ¡Hola!
 * Gracias por ver mi código. No es muy bonito, pero es lo que hay ;) ¡Saludos!
 * -- Eduardo, @carnby
 */

{% include "javascript/require-config.js" %}

require(['d3', 'masonry', 'imagesLoaded', 'aurora'], function(d3, masonry, imagesLoaded, aurora) {

    var spinner = aurora.spinner('public-portraits');

    var display_portraits = function(data) {
        var div = d3.select('#public-portraits');
        var thumb = div.selectAll('div.portrait-demo').data(data);

        thumb.enter().append('div').classed('portrait-demo', true).style({'width': '183px', 'margin-bottom': 5, 'margin-left': 15, 'display': 'block', 'opacity': 0});
        thumb.html(function(d) {
            return '<div class="thumbnail"><a href="' + d.portrait_url + '"><img style="width: 100%;" class="img img-rounded" src="' + d.profile_image_url.replace('normal', '400x400') + '" /></a>' +
                '<div class="caption">' +
                    '<h3><a href="' + d.portrait_url + '">@' + d.screen_name + '</a></h3>' +
                    '<p>' + d.description + '</p>' +
                    //'<p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>' +
                '</div></div>';
        });

        imagesLoaded('#public-portraits').on('always', function(instance) {
            masonry_instance = new masonry('#public-portraits', {
                itemSelector: '.portrait-demo',
                columnWidth: 186
            });
            spinner.stop();
            thumb.transition().style('opacity', 1);
        });
    };

    var retry = 1000;
    var load_portraits = function() {
        d3.json('{% url 'portraits:get-public-portraits' %}', function(error, data) {
            if (data != null) {
                console.log(data, imagesLoaded);
                display_portraits(data);
            } else {
                if (retry <= 10000) {
                    setTimeout(load_portraits, retry);
                    retry += 500;
                } else {
                    alert('Ocurrió un error. Por favor carga la página de nuevo.');
                }

            }
        });
    };

    load_portraits();
});
</script>
{% endblock %}

django_project/virtualornithology/portraits/templates/portraits/protected.html
{% extends "portraits/index.html" %}

{% block body_content %}
<div id="profile"></div>

<div class="alert alert-danger" role="alert"><p><strong>Este perfil es privado.</strong> Solamente <strong>@{{ portrait_screen_name }}</strong> puede acceder a él.</p></div>

{% endblock body_content %}

{% block footer_script %}
<script>
/**
 * ¡Hola!
 * Gracias por ver mi código. No es muy bonito, pero es lo que hay ;) ¡Saludos!
 * -- Eduardo, @carnby
 */

{% include "timelines/require-config.js" %}

require.config({
    'paths': {
        'portrait_graph': '{{ STATIC_URL }}vis/matta.portrait',
        'matta_circlepack': '{{ STATIC_URL }}vis/matta.recommendations',
        'seedrandom': '{{ STATIC_URL }}libs/seedrandom.min'
    }
});

require(['d3', 'portrait_graph', 'matta_circlepack', 'seedrandom', 'matta', 'aurora', 'moment'],
function(d3, portrait_graph, portrait_recommendations, seedrandom, matta, aurora, moment) {
    d3.select('#profile').datum(JSON.parse({{ profile_data }}))
            .html(function (d) {
                var name = '@' + d.screen_name;
                if (d.name && d.name != '') {
                    name += ' <br /><small>' + d.name + '</small>';
                }

                return '<a target="_blank" class="profile" href="https://twitter.com/intent/user?screen_name=' + d.screen_name + '">' +
                        '<img class="img img-circle" width="128" height="128" src="' + d.profile_image_url.replace('normal', '400x400') + '">' +
                        '</a>' +
                        '<h2>' +
                        '<a target="_blank" class="profile" href="https://twitter.com/intent/user?screen_name=' + d.screen_name + '">' + name + '</a>' +
                        '</h2>' +
                        '<p>' + d.description + '</p>';
            });
});
</script>
{% endblock footer_script %}

django_project/virtualornithology/portraits/templates/portraits/users.html
{% extends "site/base.html" %}

{% block header %}
<script type="text/javascript" src="{{ STATIC_URL }}libs/d3.layout.cloud.js"></script>

<style>
div.popover {
    width: 312px;
    max-width: 312px;
}

div.container-fluid {
    margin: auto;
    max-width: 1100px;
    width: 1100px;
}

.tweet a {
    color: #333;
}

.tweet .text {
    margin-top: 3px;
    font-family: Georgia, 'Times New Roman', Palatino, serif;
    font-size: 18px;
    line-height: 24px;
    color: #333;
}

.tweet .time {
    color: #707070;
    font-family: 'Helvetica Neue', Arial, sans-serif;
    font-size: 12px;
    line-height: 16px;
}

.tweet a .full-name {
    font-size: 16px;
    line-height: 16px;
}

.tweet a .screen-name {
    color: #666;
    font-size: 14px;
    line-height: 18px;
}

</style>

{% endblock%}

{% block content %}
<div class="row-fluid">
    <div class="span12">
        <div id="network"></div>
    </div>
  </div>
{% endblock %}

{% block scripts %}
<script type="text/coffeescript" src='{{ STATIC_URL }}vis/twitter-entities.coffee'></script>
<script type="text/coffeescript" src='{{ STATIC_URL }}vis/force-directed-graph.coffee'></script>
<script type="text/coffeescript">

# considerar esto http://bl.ocks.org/mbostock/1804919

color = d3.scale.category20()
node_radius = 24

width = 1200
height = 520

force_directed = window.aleph.force_directed()
    .clamp_to_viewport(true)
    .width(width)
    .height(height)
    .node_radius(24)


svg = d3.select("#network").append("svg")
    .attr("width", width)
    .attr("height", height)


defs = svg.append('defs')

defs.append('clipPath').attr('id', 'clip-circle').append('circle')
    .attr('r', node_radius - 3)
    .attr('cx', node_radius)
    .attr('cy', node_radius)


force_directed.painter((node) ->
    node.append('circle')
        .attr('cx', node_radius)
        .attr('cy', node_radius)
        .attr('r', node_radius)
        .attr('fill', (d) -> color(0))
        .attr('stroke', 'black')
        .attr('stroke-width', 1)
    
    node.on('click', (e) ->
        console.log 'e', e
        position = 'top'
        if e.y <= (height * 0.5)
            position = 'bottom'
        aleph.show_tweet(@, e.tweets[0], position)
    )

    node.append("image")
        .attr('xlink:href', (d) -> d.fields.profile_image_url)
        .attr('width', node_radius * 2)
        .attr('height', node_radius * 2)
        .attr('clip-path', 'url(#clip-circle)')

    node.append("title")
        .text((d) -> d.fields.name)
)

d3.json("/api/portraits/ego-network/#{40}", (error, graph) ->
    console.log graph

    d3.select('#dt-count-nodes').text(graph.nodes.length)
    d3.select('#dt-count-links').text(graph.links.length)

    id_map = {}
    node_map = {}


    graph.nodes.forEach (n, i) ->
        n = graph.nodes[i]
        id_map[n.pk] = i
        node_map[i] = n
        n.key = n.pk
        n.pk = i
        n.r = node_radius
        n.tweets = []


    graph.tweets.forEach (tweet, i) ->
        console.log tweet
        if tweet?
            author = graph.nodes[id_map[tweet.fields.user]]
            tweet.fields.user = graph.nodes[id_map[tweet.fields.user]]
            author.tweets.push(tweet)
     
    console.log 'tweets', graph.tweets

    console.log id_map

    graph.links.forEach (l) ->
        l.source = id_map[l.source]
        l.target = id_map[l.target]

    svg.datum(graph).call(force_directed)
)
</script>
{% endblock %}